### ISSUE TITLE
Install via composer

### ISSUE THREAD

**Issue by radzserg** [crocodoc/php-box-view#3]
Have you upload your package to https://packagist.org/ cannot find it there. So that

 composer require crocodoc/php-box-view
 composer require crocodoc/box-view
generate
Could not find package vendor at any version
error

also what is the difference between this and https://github.com/crocodoc/crocodoc-php libs

**Comment by bgoldman** [comment]
It's up there now!

**Comment by bgoldman** [comment]
Also, the difference between this and crocodoc-php is that this uses the new Box View APIs while crocodoc-php uses the old Crocodoc APIs.

**Comment by radzserg** [comment]
Thanks, also is it a way to get document content 
equivalent to old 
CrocodocDownload::text($uuid);
? Didnt' find it but this functionality is really important.

**Comment by bgoldman** [comment]
This functionality doesn't exist in the new Box View API, unfortunately.

**Comment by radzserg** [comment]
radzserg@radzserg-laptop:~/projects/vendori.local$ composer require crocodoc/php-box-view 
Using version ^1.0 for crocodoc/php-box-view           
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)          
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for crocodoc/php-box-view ^1.0 -> satisfiable by crocodoc/php-box-view[1.0.0].
    - crocodoc/php-box-view 1.0.0 requires guzzlehttp/guzzle ~5.2 -> no matching package found.
There's a new issue

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.


Update the version of guzzle dependency. This should solve this error.
 "require": {
    "guzzlehttp/guzzle": "~5.3"
